title: <p align="center"> Jorge Aliaga Luque </p>

logo: "/images/logo.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_Jorge Aliaga Luque (English).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jorge-aliaga-luque/">LinkedIn</a> |
  <a href="https://github.com/jorgealiaga36/machine_learning">GitHub</a>
  </p>
  
  <p align="justify">
  Hard-working and decisive person with experience in software development through participation in electronic defence projects.
  <br><br>
  Strong interest in Data Science and machine learning, with a desire to train in this field at a professional level.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
